### ISSUE TITLE
Make the interdomain pipe non-blocking

### ISSUE THREAD

**Issue by haesbaert** [robur-coop/miou#25]
Heya, the fix in 29cb3d00d40bbfdffbd30fad84f886a9e0a33e7b is odd.

You can just make the pipe non-blocking, and if write returns EAGAIN, you ignore (there's pending stuff), you don't need the `interrupted` thing at all.

Just a suggestion, unless I missed something.

**Comment by dinosaure** [comment]
> the pipe non-blocking, and if write returns EAGAIN

Ah yes, it can save an atomic and delay everything to the system, I will try to propose something soon. Thanks for your report :+1:.
